# Generated by Django 3.2.12 on 2024-01-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_event1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Event1',
        ),
    ]
