# Generated by Django 3.2.12 on 2024-01-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_subpack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subpack',
        ),
    ]
